// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQGpg0aEm0qr7aPI_9jEnRL9o2MTIwbU',
    appId: '1:550790884938:web:6bae05cb532d6ad6f1c0b3',
    messagingSenderId: '550790884938',
    projectId: 'flutterprectice',
    authDomain: 'flutterprectice.firebaseapp.com',
    storageBucket: 'flutterprectice.appspot.com',
    measurementId: 'G-C6Q353PJ9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFmfczyPRu7DMbif8_k7l_5Ch_U84VZSE',
    appId: '1:550790884938:android:e5f1b6f4e86e0444f1c0b3',
    messagingSenderId: '550790884938',
    projectId: 'flutterprectice',
    storageBucket: 'flutterprectice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5OvvP1mK8FloJAg_T6EGN4h2TcpUwrc',
    appId: '1:550790884938:ios:80d97e5164023185f1c0b3',
    messagingSenderId: '550790884938',
    projectId: 'flutterprectice',
    storageBucket: 'flutterprectice.appspot.com',
    iosClientId: '550790884938-uubs69i2o231gf37iu3fg268unnngq5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb5OvvP1mK8FloJAg_T6EGN4h2TcpUwrc',
    appId: '1:550790884938:ios:80d97e5164023185f1c0b3',
    messagingSenderId: '550790884938',
    projectId: 'flutterprectice',
    storageBucket: 'flutterprectice.appspot.com',
    iosClientId: '550790884938-uubs69i2o231gf37iu3fg268unnngq5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo3',
  );
}
